export const CATEGORIES_LOADING = 'CATEGORIES_LOADING';
export const CATEGORIES_SUCCESS = 'CATEGORIES_SUCCESS';
export const CATEGORIES_STOP = 'CATEGORIES_STOP';
export const CATEGORIES_FAIL = 'CATEGORIES_FAIL';
